# Basic Python

## 1. Split this string

In [61]:
s = "Hi there Sam!"

In [62]:
s="Hi there Sam!"
s=s.split()
print(s);

['Hi', 'there', 'Sam!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [63]:
planet = "Earth"
diameter = 12742

In [64]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [65]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [66]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [67]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [68]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [69]:
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [70]:
import numpy as np
array=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [71]:
arr = np.arange(0,9).reshape(3,3)

print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [72]:
import numpy as np 
a = np.array([1,2,3]) 

print ('First array;')
print (a)
b = np.array([4,5,6]) 

print ('Second array;')
print (b) 
# both the arrays are of same dimensions 

print ('Joining the two arrays along axis 0:')
print (a,b)

First array;
[1 2 3]
Second array;
[4 5 6]
Joining the two arrays along axis 0:
[1 2 3] [4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [73]:
import pandas as pd

In [74]:
import pandas as pd

from numpy.random import randn
 
df = pd.DataFrame(randn(3,2), columns=['column 1', 'column 2'], index = ['row 1', 'row 2','row 3'])
print(df)

       column 1  column 2
row 1 -0.342042  0.420559
row 2 -1.149391 -1.168271
row 3 -1.287335  0.964224


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [75]:
import datetime

def date_generator():
  from_date = datetime.datetime.today()
  while True:
    yield from_date
    from_date = from_date - datetime.timedelta(days=1)

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [76]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [77]:
import pandas as pd  
      

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
  
 
df = pd.DataFrame(lists, columns=['Tag', 'name','number']) 
print(df )

   Tag name  number
0    1  aaa      22
1    2  bbb      25
2    3  ccc      24
